[project]
authors = ["TilliFe <tillmann.fehrenbach@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "pytorch"]
description = "Add a short description here"
name = "Endia"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
pytorch = ">=2.4.0,<3"
graphviz = ">=12.0.0,<13"
